// src/quantum/qasm.ts
// Multi-Framework Code Export: Qiskit, PennyLane, Cirq, OpenQASM (F4, F16, F23)
import { CircuitGate } from '../types';

export function exportToQASM(numQubits: number, gates: CircuitGate[]): string {
  const lines: string[] = [
    'OPENQASM 2.0;',
    'include "qelib1.inc";',
    '',
    `qreg q[${numQubits}];`,
    `creg c[${numQubits}];`,
    ''
  ];

  const sortedGates = [...gates].sort((a, b) => a.stepIndex - b.stepIndex);

  for (const gate of sortedGates) {
    const { type, targets, controls, params } = gate;
    switch (type) {
      case 'H':
        lines.push(`h q[${targets[0]}];`);
        break;
      case 'X':
        lines.push(`x q[${targets[0]}];`);
        break;
      case 'Y':
        lines.push(`y q[${targets[0]}];`);
        break;
      case 'Z':
        lines.push(`z q[${targets[0]}];`);
        break;
      case 'S':
        lines.push(`s q[${targets[0]}];`);
        break;
      case 'S_DAG':
        lines.push(`sdg q[${targets[0]}];`);
        break;
      case 'T':
        lines.push(`t q[${targets[0]}];`);
        break;
      case 'T_DAG':
        lines.push(`tdg q[${targets[0]}];`);
        break;
      case 'RX':
        lines.push(`rx(${params?.theta ?? 3.14159}) q[${targets[0]}];`);
        break;
      case 'RY':
        lines.push(`ry(${params?.theta ?? 3.14159}) q[${targets[0]}];`);
        break;
      case 'RZ':
        lines.push(`rz(${params?.theta ?? 3.14159}) q[${targets[0]}];`);
        break;
      case 'CX':
        if (controls && controls.length > 0) {
          lines.push(`cx q[${controls[0]}], q[${targets[0]}];`);
        }
        break;
      case 'CZ':
        if (controls && controls.length > 0) {
          lines.push(`cz q[${controls[0]}], q[${targets[0]}];`);
        }
        break;
      case 'SWAP':
        if (targets.length >= 2) {
          lines.push(`swap q[${targets[0]}], q[${targets[1]}];`);
        }
        break;
      case 'CCX':
        if (controls && controls.length >= 2) {
          lines.push(`ccx q[${controls[0]}], q[${controls[1]}], q[${targets[0]}];`);
        }
        break;
      case 'MEASURE':
        lines.push(`measure q[${targets[0]}] -> c[${targets[0]}];`);
        break;
      default:
        break;
    }
  }

  return lines.join('\n');
}

export function exportToQiskit(numQubits: number, gates: CircuitGate[]): string {
  const lines: string[] = [
    '# Generated by QuantumLearn (https://quantumlearn.ai)',
    'from qiskit import QuantumCircuit, transpile',
    'from qiskit_aer import AerSimulator',
    'from qiskit.visualization import plot_histogram',
    'import numpy as np',
    '',
    `# Initialize Quantum Circuit with ${numQubits} qubits`,
    `qc = QuantumCircuit(${numQubits}, ${numQubits})`,
    ''
  ];

  const sortedGates = [...gates].sort((a, b) => a.stepIndex - b.stepIndex);

  for (const gate of sortedGates) {
    const { type, targets, controls, params } = gate;
    switch (type) {
      case 'H':
        lines.push(`qc.h(${targets[0]})`);
        break;
      case 'X':
        lines.push(`qc.x(${targets[0]})`);
        break;
      case 'Y':
        lines.push(`qc.y(${targets[0]})`);
        break;
      case 'Z':
        lines.push(`qc.z(${targets[0]})`);
        break;
      case 'S':
        lines.push(`qc.s(${targets[0]})`);
        break;
      case 'S_DAG':
        lines.push(`qc.sdg(${targets[0]})`);
        break;
      case 'T':
        lines.push(`qc.t(${targets[0]})`);
        break;
      case 'T_DAG':
        lines.push(`qc.tdg(${targets[0]})`);
        break;
      case 'RX':
        lines.push(`qc.rx(${params?.theta ?? 'np.pi'}, ${targets[0]})`);
        break;
      case 'RY':
        lines.push(`qc.ry(${params?.theta ?? 'np.pi'}, ${targets[0]})`);
        break;
      case 'RZ':
        lines.push(`qc.rz(${params?.theta ?? 'np.pi'}, ${targets[0]})`);
        break;
      case 'CX':
        if (controls && controls.length > 0) {
          lines.push(`qc.cx(${controls[0]}, ${targets[0]})`);
        }
        break;
      case 'CZ':
        if (controls && controls.length > 0) {
          lines.push(`qc.cz(${controls[0]}, ${targets[0]})`);
        }
        break;
      case 'SWAP':
        if (targets.length >= 2) {
          lines.push(`qc.swap(${targets[0]}, ${targets[1]})`);
        }
        break;
      case 'CCX':
        if (controls && controls.length >= 2) {
          lines.push(`qc.ccx(${controls[0]}, ${controls[1]}, ${targets[0]})`);
        }
        break;
      case 'MEASURE':
        lines.push(`qc.measure(${targets[0]}, ${targets[0]})`);
        break;
      default:
        break;
    }
  }

  lines.push('');
  lines.push('# Measure all qubits if not explicitly measured');
  lines.push('qc.measure_all()');
  lines.push('');
  lines.push('# Simulate on local Aer simulator');
  lines.push('simulator = AerSimulator()');
  lines.push('compiled_circuit = transpile(qc, simulator)');
  lines.push('result = simulator.run(compiled_circuit, shots=1024).result()');
  lines.push('counts = result.get_counts()');
  lines.push('print("Measurement Counts:", counts)');

  return lines.join('\n');
}

// F4 + F16 + F23: PennyLane Export
export function exportToPennyLane(numQubits: number, gates: CircuitGate[]): string {
  const lines: string[] = [
    '# Generated by QuantumLearn – PennyLane Framework (F4: Multi-Framework Engine)',
    'import pennylane as qml',
    'import numpy as np',
    '',
    `# Initialize device with ${numQubits} qubits`,
    `dev = qml.device("default.qubit", wires=${numQubits}, shots=1024)`,
    '',
    '@qml.qnode(dev)',
    'def quantum_circuit():',
  ];

  const sortedGates = [...gates].sort((a, b) => a.stepIndex - b.stepIndex);

  for (const gate of sortedGates) {
    const { type, targets, controls, params } = gate;
    switch (type) {
      case 'H':
        lines.push(`    qml.Hadamard(wires=${targets[0]})`);
        break;
      case 'X':
        lines.push(`    qml.PauliX(wires=${targets[0]})`);
        break;
      case 'Y':
        lines.push(`    qml.PauliY(wires=${targets[0]})`);
        break;
      case 'Z':
        lines.push(`    qml.PauliZ(wires=${targets[0]})`);
        break;
      case 'S':
        lines.push(`    qml.S(wires=${targets[0]})`);
        break;
      case 'T':
        lines.push(`    qml.T(wires=${targets[0]})`);
        break;
      case 'RX':
        lines.push(`    qml.RX(${params?.theta ?? 'np.pi'}, wires=${targets[0]})`);
        break;
      case 'RY':
        lines.push(`    qml.RY(${params?.theta ?? 'np.pi'}, wires=${targets[0]})`);
        break;
      case 'RZ':
        lines.push(`    qml.RZ(${params?.theta ?? 'np.pi'}, wires=${targets[0]})`);
        break;
      case 'CX':
        if (controls && controls.length > 0)
          lines.push(`    qml.CNOT(wires=[${controls[0]}, ${targets[0]}])`);
        break;
      case 'CZ':
        if (controls && controls.length > 0)
          lines.push(`    qml.CZ(wires=[${controls[0]}, ${targets[0]}])`);
        break;
      case 'SWAP':
        if (targets.length >= 2)
          lines.push(`    qml.SWAP(wires=[${targets[0]}, ${targets[1]}])`);
        break;
      case 'CCX':
        if (controls && controls.length >= 2)
          lines.push(`    qml.Toffoli(wires=[${controls[0]}, ${controls[1]}, ${targets[0]}])`);
        break;
      default:
        break;
    }
  }

  lines.push(`    return qml.probs(wires=list(range(${numQubits})))`);
  lines.push('');
  lines.push('# Execute and print results');
  lines.push('result = quantum_circuit()');
  lines.push('print("State Probabilities:", result)');
  lines.push('');
  lines.push('# Draw the circuit diagram');
  lines.push('print(qml.draw(quantum_circuit)())');

  return lines.join('\n');
}

// F4 + F16 + F23: Cirq Export
export function exportToCirq(numQubits: number, gates: CircuitGate[]): string {
  const lines: string[] = [
    '# Generated by QuantumLearn – Cirq Framework (F4: Multi-Framework Engine)',
    'import cirq',
    'import numpy as np',
    '',
    `# Initialize ${numQubits} line qubits`,
    `qubits = cirq.LineQubit.range(${numQubits})`,
  ];
  const q = (i: number) => `qubits[${i}]`;

  const sortedGates = [...gates].sort((a, b) => a.stepIndex - b.stepIndex);
  const moments: string[] = [];

  for (const gate of sortedGates) {
    const { type, targets, controls, params } = gate;
    switch (type) {
      case 'H':
        moments.push(`    cirq.H(${q(targets[0])}),`);
        break;
      case 'X':
        moments.push(`    cirq.X(${q(targets[0])}),`);
        break;
      case 'Y':
        moments.push(`    cirq.Y(${q(targets[0])}),`);
        break;
      case 'Z':
        moments.push(`    cirq.Z(${q(targets[0])}),`);
        break;
      case 'S':
        moments.push(`    cirq.S(${q(targets[0])}),`);
        break;
      case 'T':
        moments.push(`    cirq.T(${q(targets[0])}),`);
        break;
      case 'RX':
        moments.push(`    cirq.rx(rads=${params?.theta ?? 'np.pi'})(${q(targets[0])}),`);
        break;
      case 'RY':
        moments.push(`    cirq.ry(rads=${params?.theta ?? 'np.pi'})(${q(targets[0])}),`);
        break;
      case 'RZ':
        moments.push(`    cirq.rz(rads=${params?.theta ?? 'np.pi'})(${q(targets[0])}),`);
        break;
      case 'CX':
        if (controls && controls.length > 0)
          moments.push(`    cirq.CNOT(${q(controls[0])}, ${q(targets[0])}),`);
        break;
      case 'CZ':
        if (controls && controls.length > 0)
          moments.push(`    cirq.CZ(${q(controls[0])}, ${q(targets[0])}),`);
        break;
      case 'SWAP':
        if (targets.length >= 2)
          moments.push(`    cirq.SWAP(${q(targets[0])}, ${q(targets[1])}),`);
        break;
      case 'CCX':
        if (controls && controls.length >= 2)
          moments.push(`    cirq.CCX(${q(controls[0])}, ${q(controls[1])}, ${q(targets[0])}),`);
        break;
      case 'MEASURE':
        moments.push(`    cirq.measure(${q(targets[0])}, key='q${targets[0]}'),`);
        break;
      default:
        break;
    }
  }

  // Add final measurements
  for (let i = 0; i < numQubits; i++) {
    moments.push(`    cirq.measure(${q(i)}, key='q${i}'),`);
  }

  lines.push('');
  lines.push('circuit = cirq.Circuit(');
  lines.push(...moments);
  lines.push(')');
  lines.push('');
  lines.push('print("Circuit:")');
  lines.push('print(circuit)');
  lines.push('');
  lines.push('# Simulate with Cirq statevector simulator');
  lines.push('simulator = cirq.Simulator()');
  lines.push('result = simulator.simulate(circuit)');
  lines.push('print("\\nFinal state vector:")');
  lines.push('print(result.final_state_vector)');
  lines.push('');
  lines.push('# Sample measurements');
  lines.push('samples = simulator.run(circuit, repetitions=1024)');
  lines.push('print("\\nMeasurement Counts:")');
  lines.push('print(samples.histogram(key="q0"))');

  return lines.join('\n');
}

// F19: Compute circuit resource metrics (gate count, depth, T-count, two-qubit gate count)
export interface CircuitResourceMetrics {
  gateCount: number;
  circuitDepth: number;
  twoQubitGates: number;
  tGates: number;
  qubitCount: number;
  parallelizationScore: number; // gates per depth layer
  estimatedFidelity: number;
  resourceSummary: string;
}

export function analyzeCircuitResources(numQubits: number, gates: CircuitGate[]): CircuitResourceMetrics {
  if (gates.length === 0) {
    return {
      gateCount: 0, circuitDepth: 0, twoQubitGates: 0, tGates: 0,
      qubitCount: numQubits, parallelizationScore: 0, estimatedFidelity: 1.0,
      resourceSummary: 'Empty circuit — add gates to begin analysis.'
    };
  }
  const twoQubitTypes = new Set(['CX', 'CZ', 'SWAP', 'CCX']);
  const tGateTypes = new Set(['T', 'T_DAG']);
  const twoQubitGates = gates.filter(g => twoQubitTypes.has(g.type)).length;
  const tGates = gates.filter(g => tGateTypes.has(g.type)).length;
  const maxStep = Math.max(...gates.map(g => g.stepIndex));
  const circuitDepth = maxStep + 1;
  const parallelizationScore = parseFloat((gates.length / Math.max(1, circuitDepth)).toFixed(2));
  // Simplified fidelity model: 0.999/gate single-qubit, 0.995/gate two-qubit
  const singleQubitGates = gates.length - twoQubitGates;
  const estimatedFidelity = parseFloat(
    (Math.pow(0.9995, singleQubitGates) * Math.pow(0.995, twoQubitGates)).toFixed(4)
  );

  let resourceSummary = `${gates.length} gates across ${circuitDepth} time steps`;
  if (twoQubitGates > 0) resourceSummary += `, ${twoQubitGates} two-qubit ops`;
  if (tGates > 0) resourceSummary += `, T-count: ${tGates}`;

  return { gateCount: gates.length, circuitDepth, twoQubitGates, tGates, qubitCount: numQubits, parallelizationScore, estimatedFidelity, resourceSummary };
}

export interface ParsedCircuitResult {
  numQubits: number;
  gates: CircuitGate[];
  lineIndexToGate: Record<number, CircuitGate>;
  lineIndexToGateIndex: Record<number, number>;
  lineIndexToGateId: Record<number, string>;
  gateIdToLineIndex: Record<string, number>;
  error: string | null;
}

export interface GatePhysicsDetails {
  gateType: string;
  title: string;
  operation: string;
  physicsSummary: string;
  stateFormula: string;
  matrixLatex: string;
  matrixGrid: string[][];
  blochAction: string;
  reversibility: string;
  entanglementRole: string;
  hardwareFidelity: string;
}

/**
 * Parses Qiskit (Python) or OpenQASM source code line-by-line into visual CircuitGates
 * and maps each line number to its corresponding gate ID.
 */
export function parseQuantumCode(code: string): ParsedCircuitResult {
  const lines = code.split('\n');
  let numQubits = 2;
  const gates: CircuitGate[] = [];
  const lineIndexToGate: Record<number, CircuitGate> = {};
  const lineIndexToGateIndex: Record<number, number> = {};
  const lineIndexToGateId: Record<number, string> = {};
  const gateIdToLineIndex: Record<string, number> = {};
  const qubitNextStep: Record<number, number> = { 0: 0, 1: 0, 2: 0, 3: 0, 4: 0 };

  // First pass: detect number of qubits
  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i].trim();
    // Qiskit: QuantumCircuit(num, ...)
    const qiskitMatch = raw.match(/QuantumCircuit\s*\(\s*(\d+)/i);
    if (qiskitMatch) {
      numQubits = Math.max(1, Math.min(5, parseInt(qiskitMatch[1], 10)));
    }
    // QASM: qreg q[num];
    const qasmMatch = raw.match(/qreg\s+\w+\s*\[\s*(\d+)\s*\]/i);
    if (qasmMatch) {
      numQubits = Math.max(1, Math.min(5, parseInt(qasmMatch[1], 10)));
    }
    // PennyLane: dev = qml.device(..., wires=num)
    const plMatch = raw.match(/wires\s*=\s*(\d+)/i);
    if (plMatch) {
      numQubits = Math.max(1, Math.min(5, parseInt(plMatch[1], 10)));
    }
  }

  const parseTheta = (paramStr?: string): number => {
    if (!paramStr) return Math.PI;
    const clean = paramStr.replace(/np\./g, '').replace(/Math\./g, '').trim();
    if (clean.includes('pi/4')) return Math.PI / 4;
    if (clean.includes('pi/2')) return Math.PI / 2;
    if (clean.includes('pi')) return Math.PI;
    const parsed = parseFloat(clean);
    return isNaN(parsed) ? Math.PI : parsed;
  };

  // Second pass: parse gates line-by-line
  for (let lineIdx = 0; lineIdx < lines.length; lineIdx++) {
    const raw = lines[lineIdx].trim();
    if (!raw || raw.startsWith('#') || raw.startsWith('//') || raw.startsWith('/*')) continue;

    let parsedGate: Omit<CircuitGate, 'id' | 'stepIndex'> | null = null;

    // 1. Qiskit Single-Qubit: qc.h(0), qc.x(1), qc.t(0), qc.s(0), etc.
    const qkSingle = raw.match(/qc\.(h|x|y|z|s|sdg|t|tdg)\s*\(\s*(\d+)\s*\)/i);
    if (qkSingle) {
      const typeMap: Record<string, any> = {
        h: 'H', x: 'X', y: 'Y', z: 'Z', s: 'S', sdg: 'S_DAG', t: 'T', tdg: 'T_DAG'
      };
      parsedGate = {
        type: typeMap[qkSingle[1].toLowerCase()],
        targets: [parseInt(qkSingle[2], 10)]
      };
    }

    // 2. Qiskit Rotations: qc.rx(theta, q), qc.ry(theta, q), qc.rz(theta, q)
    const qkRot = raw.match(/qc\.(rx|ry|rz)\s*\(\s*([^,]+)\s*,\s*(\d+)\s*\)/i);
    if (qkRot) {
      const typeMap: Record<string, any> = { rx: 'RX', ry: 'RY', rz: 'RZ' };
      parsedGate = {
        type: typeMap[qkRot[1].toLowerCase()],
        targets: [parseInt(qkRot[3], 10)],
        params: { theta: parseTheta(qkRot[2]) }
      };
    }

    // 3. Qiskit Two-Qubit: qc.cx(0, 1), qc.cz(0, 1), qc.swap(0, 1)
    const qkTwo = raw.match(/qc\.(cx|cz|swap)\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)/i);
    if (qkTwo) {
      const gateType = qkTwo[1].toUpperCase() as any;
      const c = parseInt(qkTwo[2], 10);
      const t = parseInt(qkTwo[3], 10);
      if (gateType === 'SWAP') {
        parsedGate = { type: 'SWAP', targets: [c, t] };
      } else {
        parsedGate = { type: gateType, targets: [t], controls: [c] };
      }
    }

    // 4. Qiskit Three-Qubit: qc.ccx(0, 1, 2)
    const qkThree = raw.match(/qc\.ccx\s*\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)/i);
    if (qkThree) {
      parsedGate = {
        type: 'CCX',
        targets: [parseInt(qkThree[3], 10)],
        controls: [parseInt(qkThree[1], 10), parseInt(qkThree[2], 10)]
      };
    }

    // 5. Qiskit Measurement: qc.measure(0, 0)
    const qkMeasure = raw.match(/qc\.measure\s*\(\s*(\d+)\s*,/i);
    if (qkMeasure) {
      parsedGate = { type: 'MEASURE', targets: [parseInt(qkMeasure[1], 10)] };
    }

    // 6. QASM Single-Qubit: h q[0];, x q[0];, etc.
    const qasmSingle = raw.match(/^(h|x|y|z|s|sdg|t|tdg)\s+q\[(\d+)\]\s*;/i);
    if (qasmSingle) {
      const typeMap: Record<string, any> = {
        h: 'H', x: 'X', y: 'Y', z: 'Z', s: 'S', sdg: 'S_DAG', t: 'T', tdg: 'T_DAG'
      };
      parsedGate = {
        type: typeMap[qasmSingle[1].toLowerCase()],
        targets: [parseInt(qasmSingle[2], 10)]
      };
    }

    // 7. QASM Rotations: rx(theta) q[0];
    const qasmRot = raw.match(/^(rx|ry|rz)\s*\(([^)]+)\)\s+q\[(\d+)\]\s*;/i);
    if (qasmRot) {
      const typeMap: Record<string, any> = { rx: 'RX', ry: 'RY', rz: 'RZ' };
      parsedGate = {
        type: typeMap[qasmRot[1].toLowerCase()],
        targets: [parseInt(qasmRot[3], 10)],
        params: { theta: parseTheta(qasmRot[2]) }
      };
    }

    // 8. QASM Two-Qubit: cx q[0], q[1];
    const qasmTwo = raw.match(/^(cx|cz|swap)\s+q\[(\d+)\]\s*,\s*q\[(\d+)\]\s*;/i);
    if (qasmTwo) {
      const gType = qasmTwo[1].toUpperCase() as any;
      const c = parseInt(qasmTwo[2], 10);
      const t = parseInt(qasmTwo[3], 10);
      if (gType === 'SWAP') {
        parsedGate = { type: 'SWAP', targets: [c, t] };
      } else {
        parsedGate = { type: gType, targets: [t], controls: [c] };
      }
    }

    // 9. QASM Measurement: measure q[0] -> c[0];
    const qasmMeasure = raw.match(/^measure\s+q\[(\d+)\]/i);
    if (qasmMeasure) {
      parsedGate = { type: 'MEASURE', targets: [parseInt(qasmMeasure[1], 10)] };
    }

    // 10. PennyLane: qml.Hadamard(wires=0)
    const plSingle = raw.match(/qml\.(Hadamard|PauliX|PauliY|PauliZ|S|T)\s*\(\s*wires\s*=\s*(\d+)\s*\)/i);
    if (plSingle) {
      const typeMap: Record<string, any> = {
        hadamard: 'H', paulix: 'X', pauliy: 'Y', pauliz: 'Z', s: 'S', t: 'T'
      };
      parsedGate = {
        type: typeMap[plSingle[1].toLowerCase()] || 'H',
        targets: [parseInt(plSingle[2], 10)]
      };
    }

    // If gate was identified, assign time step and id
    if (parsedGate) {
      const gateTargets = parsedGate.targets.filter(t => t < numQubits);
      const gateControls = (parsedGate.controls || []).filter(c => c < numQubits);
      if (gateTargets.length === 0) continue;

      const involvedWires = [...gateTargets, ...gateControls];
      const maxWireStep = Math.max(...involvedWires.map(w => qubitNextStep[w] || 0));
      const stepIndex = maxWireStep;

      const gateId = `gate_${Date.now()}_L${lineIdx}_${Math.random().toString(36).substring(2, 6)}`;
      const completeGate: CircuitGate = {
        id: gateId,
        type: parsedGate.type,
        targets: gateTargets,
        controls: gateControls.length > 0 ? gateControls : undefined,
        params: parsedGate.params,
        stepIndex
      };

      gates.push(completeGate);
      lineIndexToGate[lineIdx] = completeGate;
      lineIndexToGateIndex[lineIdx] = gates.length - 1;
      lineIndexToGateId[lineIdx] = gateId;
      gateIdToLineIndex[gateId] = lineIdx;

      // Update wires next available step
      involvedWires.forEach(w => {
        qubitNextStep[w] = stepIndex + 1;
      });
    }
  }

  return {
    numQubits,
    gates,
    lineIndexToGate,
    lineIndexToGateIndex,
    lineIndexToGateId,
    gateIdToLineIndex,
    error: gates.length === 0 ? 'No quantum gate statements found in code.' : null
  };
}

/**
 * Deep physics and mathematical explanation for a specific locked quantum code line.
 */
export function getGatePhysicsExplanation(gate: CircuitGate): GatePhysicsDetails {
  const tStr = gate.targets.map(t => `q[${t}]`).join(', ');
  const cStr = gate.controls?.map(c => `q[${c}]`).join(', ') || '';

  switch (gate.type) {
    case 'H':
      return {
        gateType: 'H',
        title: `Hadamard Gate (H) on ${tStr}`,
        operation: `qc.h(${gate.targets[0]})`,
        physicsSummary: `Creates maximum quantum superposition. It converts definite basis states into equal linear combinations with orthogonal phase relations. Transforms the computational Z-basis into the transverse X-basis (|+⟩ and |-⟩).`,
        stateFormula: `|0⟩ → (|0⟩ + |1⟩)/√2 = |+⟩,   |1⟩ → (|0⟩ - |1⟩)/√2 = |-⟩`,
        matrixLatex: `\\frac{1}{\\sqrt{2}}\\begin{pmatrix} 1 & 1 \\\\ 1 & -1 \\end{pmatrix}`,
        matrixGrid: [['1/√2', '1/√2'], ['1/√2', '-1/√2']],
        blochAction: `Rotates the state vector by π (180°) around the diagonal (X + Z)/√2 axis of the Bloch sphere, flipping North Pole (|0⟩) to the +X Equator (|+⟩).`,
        reversibility: `Self-inverse: H² = I (applying H twice restores the original state).`,
        entanglementRole: `The cornerstone of entanglement: applying H to control followed by CNOT creates a maximally entangled Bell State.`,
        hardwareFidelity: `High (~99.95% on superconducting transmons via microwave drive pulses).`
      };

    case 'X':
      return {
        gateType: 'X',
        title: `Pauli-X (NOT / Bit-Flip) on ${tStr}`,
        operation: `qc.x(${gate.targets[0]})`,
        physicsSummary: `The quantum analogue of a classical NOT gate. It flips the amplitude coefficients of |0⟩ and |1⟩, exchanging probability amplitudes.`,
        stateFormula: `|0⟩ → |1⟩,   |1⟩ → |0⟩`,
        matrixLatex: `\\begin{pmatrix} 0 & 1 \\\\ 1 & 0 \\end{pmatrix}`,
        matrixGrid: [['0', '1'], ['1', '0']],
        blochAction: `Rotates the state vector by 180° (π radians) about the X-axis of the Bloch sphere.`,
        reversibility: `Self-inverse: X² = I.`,
        entanglementRole: `Used to prepare initial active states |1⟩ and in parity checks.`,
        hardwareFidelity: `Extremely high (>99.96% via standard π-pulse microwave envelope).`
      };

    case 'Y':
      return {
        gateType: 'Y',
        title: `Pauli-Y (Bit & Phase Flip) on ${tStr}`,
        operation: `qc.y(${gate.targets[0]})`,
        physicsSummary: `Simultaneously applies a bit-flip and a phase-flip with an imaginary phase factor i. Maps |0⟩ → i|1⟩ and |1⟩ → -i|0⟩.`,
        stateFormula: `|0⟩ → i|1⟩,   |1⟩ → -i|0⟩`,
        matrixLatex: `\\begin{pmatrix} 0 & -i \\\\ i & 0 \\end{pmatrix}`,
        matrixGrid: [['0', '-i'], ['i', '0']],
        blochAction: `Rotates the state vector by 180° about the Y-axis of the Bloch sphere.`,
        reversibility: `Self-inverse: Y² = I.`,
        entanglementRole: `Generates imaginary phase superpositions; critical in quantum error correction syndromes.`,
        hardwareFidelity: `High (~99.92%).`
      };

    case 'Z':
      return {
        gateType: 'Z',
        title: `Pauli-Z (Phase-Flip) on ${tStr}`,
        operation: `qc.z(${gate.targets[0]})`,
        physicsSummary: `Leaves the computational state |0⟩ completely untouched, but multiplies the phase of state |1⟩ by -1 (180° phase flip). In the superposition basis, it swaps |+⟩ ↔ |-⟩.`,
        stateFormula: `|0⟩ → |0⟩,   |1⟩ → -|1⟩`,
        matrixLatex: `\\begin{pmatrix} 1 & 0 \\\\ 0 & -1 \\end{pmatrix}`,
        matrixGrid: [['1', '0'], ['0', '-1']],
        blochAction: `Rotates the state vector by 180° around the Z-axis (Equator longitude inversion).`,
        reversibility: `Self-inverse: Z² = I.`,
        entanglementRole: `Core for phase-kickback mechanisms in Deutsch-Jozsa and Grover's algorithm.`,
        hardwareFidelity: `Virtual Z-gate: 100% fidelity with 0 ns physical pulse time via frame changes in software!`
      };

    case 'S':
      return {
        gateType: 'S',
        title: `Phase Gate (S = √Z) on ${tStr}`,
        operation: `qc.s(${gate.targets[0]})`,
        physicsSummary: `Adds a 90° (π/2 radians) phase shift to the |1⟩ state. Squares to the Pauli-Z gate: S² = Z.`,
        stateFormula: `|0⟩ → |0⟩,   |1⟩ → i|1⟩`,
        matrixLatex: `\\begin{pmatrix} 1 & 0 \\\\ 0 & i \\end{pmatrix}`,
        matrixGrid: [['1', '0'], ['0', 'i']],
        blochAction: `Rotates the state vector by 90° clockwise around the Z-axis of the Bloch sphere.`,
        reversibility: `Inverse is S† (S-Dagger): S · S† = I.`,
        entanglementRole: `Member of the Clifford group; used in stabilizer quantum codes.`,
        hardwareFidelity: `Virtual phase change (near 100%).`
      };

    case 'T':
      return {
        gateType: 'T',
        title: `T Gate (π/8 / Magic Gate) on ${tStr}`,
        operation: `qc.t(${gate.targets[0]})`,
        physicsSummary: `Applies a 45° (π/4 radians) phase shift to the |1⟩ component. This is a non-Clifford gate, strictly required to achieve universal quantum computing. In fault-tolerant quantum computers, T-gates require magic state distillation.`,
        stateFormula: `|0⟩ → |0⟩,   |1⟩ → e^{i\\pi/4}|1⟩ = \\frac{1+i}{\\sqrt{2}}|1⟩`,
        matrixLatex: `\\begin{pmatrix} 1 & 0 \\\\ 0 & e^{i\\pi/4} \\end{pmatrix}`,
        matrixGrid: [['1', '0'], ['0', 'e^(iπ/4)']],
        blochAction: `Rotates the state vector by 45° around the Z-axis.`,
        reversibility: `Inverse is T†: T · T† = I.`,
        entanglementRole: `Provides universality beyond the efficient classical simulatability of the Clifford group (Gottesman-Knill Theorem).`,
        hardwareFidelity: `Virtual phase rotation on superconducting qubits.`
      };

    case 'CX':
      return {
        gateType: 'CX',
        title: `Controlled-NOT (CNOT / CX) from ${cStr} → ${tStr}`,
        operation: `qc.cx(${gate.controls?.[0] ?? 0}, ${gate.targets[0]})`,
        physicsSummary: `Entangles two qubits. If the control qubit is |1⟩, it applies Pauli-X (NOT) to the target qubit; otherwise, leaves target unchanged. Entanglement creates correlations that cannot be factored into independent subsystems.`,
        stateFormula: `|00⟩ → |00⟩,  |01⟩ → |01⟩,  |10⟩ → |11⟩,  |11⟩ → |10⟩`,
        matrixLatex: `\\begin{pmatrix} 1 & 0 & 0 & 0 \\\\ 0 & 1 & 0 & 0 \\\\ 0 & 0 & 0 & 1 \\\\ 0 & 0 & 1 & 0 \\end{pmatrix}`,
        matrixGrid: [['1','0','0','0'], ['0','1','0','0'], ['0','0','0','1'], ['0','0','1','0']],
        blochAction: `Two-qubit non-local unitary; cannot be represented as single-qubit Bloch sphere rotation. Causes mutual entanglement entropy increase.`,
        reversibility: `Self-inverse: CX² = I.`,
        entanglementRole: `The primary entangler for Bell states, GHZ states, teleportation, and quantum arithmetic.`,
        hardwareFidelity: `~98.5% - 99.4% (implemented via Cross-Resonance pulse or capacitive coupling). Primary source of hardware decoherence in NISQ circuits.`
      };

    case 'CZ':
      return {
        gateType: 'CZ',
        title: `Controlled-Phase (CZ) between ${cStr} and ${tStr}`,
        operation: `qc.cz(${gate.controls?.[0] ?? 0}, ${gate.targets[0]})`,
        physicsSummary: `Flips the phase of state |11⟩ by -1. Symmetric between both qubits. Equivalent to CNOT conjugated by Hadamard on the target.`,
        stateFormula: `|11⟩ → -|11⟩, all other basis states unchanged.`,
        matrixLatex: `\\begin{pmatrix} 1 & 0 & 0 & 0 \\\\ 0 & 1 & 0 & 0 \\\\ 0 & 0 & 1 & 0 \\\\ 0 & 0 & 0 & -1 \\end{pmatrix}`,
        matrixGrid: [['1','0','0','0'], ['0','1','0','0'], ['0','0','1','0'], ['0','0','0','-1']],
        blochAction: `Non-local entangling conditional phase shift.`,
        reversibility: `Self-inverse: CZ² = I.`,
        entanglementRole: `Natural native two-qubit gate in neutral atom and superconducting architectures.`,
        hardwareFidelity: `~99.0% - 99.5%.`
      };

    case 'SWAP':
      return {
        gateType: 'SWAP',
        title: `SWAP Gate between ${tStr}`,
        operation: `qc.swap(${gate.targets[0]}, ${gate.targets[1] ?? 1})`,
        physicsSummary: `Exchanges the quantum states of two wires: |a⟩|b⟩ → |b⟩|a⟩. Can be compiled into 3 alternating CNOT gates.`,
        stateFormula: `|01⟩ ↔ |10⟩;  |00⟩ and |11⟩ unchanged.`,
        matrixLatex: `\\begin{pmatrix} 1 & 0 & 0 & 0 \\\\ 0 & 0 & 1 & 0 \\\\ 0 & 1 & 0 & 0 \\\\ 0 & 0 & 0 & 1 \\end{pmatrix}`,
        matrixGrid: [['1','0','0','0'], ['0','0','1','0'], ['0','1','0','0'], ['0','0','0','1']],
        blochAction: `Full state interchange between physical qubit registers.`,
        reversibility: `Self-inverse: SWAP² = I.`,
        entanglementRole: `Crucial for qubit routing on hardware with limited physical connectivity graph.`,
        hardwareFidelity: `~97% - 98.5% (composed of 3 CNOT passes).`
      };

    case 'RX':
    case 'RY':
    case 'RZ':
      const angle = (gate.params?.theta ?? Math.PI);
      const angleFormatted = `${(angle / Math.PI).toFixed(2)}π rad (${(angle * 180 / Math.PI).toFixed(0)}°)`;
      return {
        gateType: gate.type,
        title: `${gate.type} Rotation (${angleFormatted}) on ${tStr}`,
        operation: `qc.${gate.type.toLowerCase()}(${(angle / Math.PI).toFixed(2)}*np.pi, ${gate.targets[0]})`,
        physicsSummary: `Continuous parametric rotation around the ${gate.type[1]}-axis of the Bloch sphere by angle θ = ${angleFormatted}. Essential for variational quantum eigensolvers (VQE) and quantum neural networks.`,
        stateFormula: `exp(-i * θ/2 * σ_${gate.type[1]})`,
        matrixLatex: `R_${gate.type[1]}(\\theta)`,
        matrixGrid: [['cos(θ/2)', '-i sin(θ/2)'], ['-i sin(θ/2)', 'cos(θ/2)']],
        blochAction: `Rotates the Bloch sphere coordinates by exactly ${angleFormatted} about the ${gate.type[1]}-axis.`,
        reversibility: `Inverted by rotating with opposite angle -θ.`,
        entanglementRole: `Ansatz parameter variation in QAOA and VQE optimizations.`,
        hardwareFidelity: `>99.9% via calibrated RF pulse duration or virtual phase offset.`
      };

    case 'MEASURE':
      return {
        gateType: 'MEASURE',
        title: `Projective Measurement (Born's Rule) on ${tStr}`,
        operation: `qc.measure(${gate.targets[0]}, c[${gate.targets[0]}])`,
        physicsSummary: `Applies von Neumann projective measurement onto the computational basis {|0⟩, |1⟩}. Irreversibly collapses quantum superposition into a classical bit according to Born's Probability Rule P(k) = |⟨k|ψ⟩|².`,
        stateFormula: `|ψ⟩ = α|0⟩ + β|1⟩  ──[MEASURE]──>  |0⟩ with prob |α|²,  or |1⟩ with prob |β|²`,
        matrixLatex: `\\Pi_0 = |0\\rangle\\langle 0|, \\quad \\Pi_1 = |1\\rangle\\langle 1|`,
        matrixGrid: [['1', '0'], ['0', '0']],
        blochAction: `Collapses the Bloch vector instantly to either the North Pole (|0⟩) or South Pole (|1⟩).`,
        reversibility: `Non-unitary & Irreversible (destroys quantum phase information).`,
        entanglementRole: `Extracts final answer; causes instantaneous collapse of entangled partner qubits.`,
        hardwareFidelity: `~97% - 99% (readout resonator assignment fidelity).`
      };

    default:
      return {
        gateType: gate.type,
        title: `${gate.type} Operation on ${tStr}`,
        operation: `qc.${gate.type.toLowerCase()}(${gate.targets[0]})`,
        physicsSummary: `Applies unitary transformation ${gate.type} to the target wire.`,
        stateFormula: `|ψ⟩ → U|ψ⟩`,
        matrixLatex: `U`,
        matrixGrid: [['1', '0'], ['0', '1']],
        blochAction: `State rotation.`,
        reversibility: `Unitary: U†U = I.`,
        entanglementRole: `State transformation.`,
        hardwareFidelity: `Standard.`
      };
  }
}
